/**
 * Meta WhatsApp Cloud API Client
 * Supports sending direct template messages or text alerts
 */

interface WhatsAppSendOptions {
  recipientPhone: string;
  message: string;
  phoneNumberId?: string;
  accessToken?: string;
}

export async function sendWhatsAppMessage({
  recipientPhone,
  message,
  phoneNumberId = process.env.WHATSAPP_PHONE_NUMBER_ID,
  accessToken = process.env.WHATSAPP_ACCESS_TOKEN,
}: WhatsAppSendOptions) {
  // Format phone number to international standard without +
  const cleanPhone = recipientPhone.replace(/\D/g, '');

  if (!phoneNumberId || !accessToken) {
    console.warn('[WhatsApp Cloud API] Missing WHATSAPP_PHONE_NUMBER_ID or WHATSAPP_ACCESS_TOKEN. Falling back to WhatsApp web link.');
    const encoded = encodeURIComponent(message);
    return {
      success: true,
      mode: 'link_fallback',
      link: `https://wa.me/${cleanPhone}?text=${encoded}`,
      message: 'Generated direct WhatsApp link (API keys not configured yet).'
    };
  }

  try {
    const url = `https://graph.facebook.com/v19.0/${phoneNumberId}/messages`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messaging_product: 'whatsapp',
        recipient_type: 'individual',
        to: cleanPhone,
        type: 'text',
        text: { body: message },
      }),
    });

    const data = await response.json();
    if (!response.ok) {
      throw new Error(data.error?.message || 'Failed to send WhatsApp message via Meta Cloud API');
    }

    return {
      success: true,
      mode: 'api',
      messageId: data.messages?.[0]?.id,
      data
    };
  } catch (error) {
    console.error('WhatsApp API Error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown WhatsApp error'
    };
  }
}

// 1. Daily 10 AM Absent List Alert
export function formatDailyAbsentAlert(dateStr: string, absentStaff: string[], lateStaff: string[]): string {
  return `📢 *Goinfi-HR Morning Attendance Digest*\n` +
         `📅 Date: ${dateStr} (10:00 AM Auto-Report)\n\n` +
         `❌ *Absent Staff (${absentStaff.length}):*\n` +
         (absentStaff.length ? absentStaff.map((name, i) => `${i + 1}. ${name}`).join('\n') : '🎉 All staff present!') +
         `\n\n⚠️ *Late Arrivals (${lateStaff.length}):*\n` +
         (lateStaff.length ? lateStaff.map((name, i) => `${i + 1}. ${name}`).join('\n') : '✅ No late arrivals.') +
         `\n\n_Auto-generated by Goinfi-HR ZKTeco Attendance System_`;
}

// 2. Real-time 30+ min Late Alert
export function formatLateAlert(employeeName: string, minutesLate: number, timeStr: string): string {
  return `🚨 *Goinfi-HR Late Arrival Alert*\n\n` +
         `Employee *${employeeName}* punched in at *${timeStr}* (${minutesLate} minutes after official start).\n\n` +
         `Please review attendance status in the dashboard: http://localhost:3000/attendance`;
}

// 3. Payslip Notification
export function formatPayslipNotification(employeeName: string, month: string, year: number, netSalary: number): string {
  return `💼 *Goinfi Technologies - Salary Payslip*\n\n` +
         `Dear *${employeeName}*,\n` +
         `Your salary for the month of *${month} ${year}* has been processed.\n\n` +
         `💰 *Net Salary:* NPR ${netSalary.toLocaleString('en-IN')}\n\n` +
         `You can download your detailed PDF payslip from your employee portal.\n` +
         `Thank you for your dedicated service!`;
}
